k9s:
  refreshRate: 2
  logBufferSize: 200
  logRequestSize: 200
  currentContext: minikube
  currentCluster: minikube
  clusters:
    minikube:
      namespace:
        active: kube-system
        favorites:
          - default
          - kube-public
          - istio-system
          - all
          - kube-system
      view:
        active: ctx
    fred:
      namespace:
        active: default
        favorites:
          - default
          - kube-public
          - istio-system
          - all
          - kube-system
      view:
        active: po
  plugins:
    sniff:
      shortCut: ShiftS
      scopes:
        - po
        - dp
      args:
        n: $NAMESPACE

